/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2.swing;

/**
 *
 * @author Mario
 */
public class AppMeteorologica extends javax.swing.JFrame {

    /**
     * Creates new form AppMeteorologica
     */
    public AppMeteorologica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radiobtnValladolid = new javax.swing.JRadioButton();
        radiobtnMadrid = new javax.swing.JRadioButton();
        radiobtnSegovia = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        comboBoxConsultas = new javax.swing.JComboBox<>();
        JbuttonEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(radiobtnValladolid);
        radiobtnValladolid.setText("Valladolid");
        radiobtnValladolid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnValladolidActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnMadrid);
        radiobtnMadrid.setText("Madrid");
        radiobtnMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMadridActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnSegovia);
        radiobtnSegovia.setText("Segovia");
        radiobtnSegovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnSegoviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiobtnValladolid)
                    .addComponent(radiobtnMadrid)
                    .addComponent(radiobtnSegovia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radiobtnValladolid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobtnMadrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobtnSegovia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("EJERCICIO 2 DEL EXAMEN DE LA 2ª EVALUACIÓN");

        comboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo actual", "Parte de lluvias", "Prevision meteorologica" }));
        comboBoxConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxConsultasActionPerformed(evt);
            }
        });

        JbuttonEnviar.setText("ENVIAR");
        JbuttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonEnviarActionPerformed(evt);
            }
        });

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        jScrollPane1.setViewportView(txtArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbuttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JbuttonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtnValladolidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnValladolidActionPerformed


    }//GEN-LAST:event_radiobtnValladolidActionPerformed

    private void comboBoxConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxConsultasActionPerformed


    }//GEN-LAST:event_comboBoxConsultasActionPerformed

    private void JbuttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonEnviarActionPerformed
        
        String ciudad = "";
        String tipoConsulta = "";
        
        // SE ESTABLECE QUE CIUDAD ESTÁ SELECCIONADA
        if (radiobtnMadrid.isSelected()){
            ciudad = "Madrid";
        } else if (radiobtnValladolid.isSelected())
        {
            ciudad = "Valladolid";
        } else if (radiobtnSegovia.isSelected())
        {
            ciudad = "Segovia";
        } else
        {
            txtArea1.append("Tienes que seleccionar al menos una ciudad");
        }
        
        // PARA SABER QUE ITEM DEL COMBOBOX ESTÁ ELEGIDO
        comboBoxConsultas.getSelectedItem();
        Object selectedItem = comboBoxConsultas.getSelectedItem();
        String ValorElegido = selectedItem.toString();
        
        String dato= "";
        if ("Tiempo actual".equals(ValorElegido)){
            dato= " es de 25 grados";
        }else if("Parte de lluvias".equals(ValorElegido)){
            dato= " es que va a llover mucho";
        }else if("Prevision meteorologica".equals(ValorElegido)){
            dato = " es que habrá viento mañana";
        }
        // SE AÑADE AL TEXT AREA LA INFORMACION DE LA CIUDAD SELECCIONADA
        txtArea1.append("\nEl " + ValorElegido + " en " + ciudad + dato);
    }//GEN-LAST:event_JbuttonEnviarActionPerformed

    private void radiobtnMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnMadridActionPerformed

    private void radiobtnSegoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnSegoviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnSegoviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AppMeteorologica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AppMeteorologica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AppMeteorologica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AppMeteorologica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMeteorologica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonEnviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtnMadrid;
    private javax.swing.JRadioButton radiobtnSegovia;
    private javax.swing.JRadioButton radiobtnValladolid;
    private javax.swing.JTextArea txtArea1;
    // End of variables declaration//GEN-END:variables
}
