/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing2;

import javax.swing.JRadioButton;

/**
 *
 * @author admin
 */
public class Ejercicio05 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio05
     */
    public Ejercicio05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtn6caras = new javax.swing.JRadioButton();
        rbtn8caras = new javax.swing.JRadioButton();
        rbtn10caras = new javax.swing.JRadioButton();
        rbtn12caras = new javax.swing.JRadioButton();
        rbtn20caras = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblDado6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Elija el tipo de dado");

        buttonGroup1.add(rbtn6caras);
        rbtn6caras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn6caras.setText("6 caras");
        rbtn6caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn6carasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn8caras);
        rbtn8caras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn8caras.setText("8 caras");

        buttonGroup1.add(rbtn10caras);
        rbtn10caras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn10caras.setText("10 caras");

        buttonGroup1.add(rbtn12caras);
        rbtn12caras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn12caras.setText("12 caras");

        buttonGroup1.add(rbtn20caras);
        rbtn20caras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn20caras.setText("20 caras");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("TIRAR DADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDado6.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Swing2\\Fotos dados\\dado6_mini.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Swing2\\Fotos dados\\dado8_mini.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Swing2\\Fotos dados\\dado10_mini.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Swing2\\Fotos dados\\dado12_mini.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Swing2\\Fotos dados\\dado20_mini.png")); // NOI18N

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultado.setText("resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbtn10caras, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rbtn12caras, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rbtn20caras))
                                            .addComponent(rbtn8caras)
                                            .addComponent(rbtn6caras))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(lblDado6)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDado6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rbtn6caras)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(rbtn8caras)
                        .addGap(76, 76, 76)
                        .addComponent(rbtn10caras)
                        .addGap(76, 76, 76)
                        .addComponent(rbtn12caras)
                        .addGap(78, 78, 78)
                        .addComponent(rbtn20caras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn6carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn6carasActionPerformed

    }//GEN-LAST:event_rbtn6carasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int numAleatorio = 0;
        String tipoDado = "";
        JRadioButton[] rdbs = {rbtn6caras, rbtn8caras, rbtn10caras, rbtn12caras, rbtn20caras};

        for (int i = 0; i < rdbs.length; i++) {

            if (rdbs[0].isSelected()) {
                tipoDado = "D6";
                numAleatorio = (int) (Math.random() * (6 + 1 - 1)) + 1;
            } else if (rdbs[1].isSelected()) {
                tipoDado = "D8";
                numAleatorio = (int) (Math.random() * (8 + 1 - 1)) + 1;
            } else if (rdbs[2].isSelected()) {
                tipoDado = "D10";
                numAleatorio = (int) (Math.random() * (10 + 1 - 1)) + 1;
            } else if (rdbs[3].isSelected()) {
                tipoDado = "D12";
                numAleatorio = (int) (Math.random() * (12 + 1 - 1)) + 1;
            } else if (rdbs[4].isSelected()) {
                tipoDado = "D20";
                numAleatorio = (int) (Math.random() * (20 + 1 - 1)) + 1;
            }
            lblResultado.setText(String.valueOf("Dado " + tipoDado + ", has sacado un " + numAleatorio));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDado6;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtn10caras;
    private javax.swing.JRadioButton rbtn12caras;
    private javax.swing.JRadioButton rbtn20caras;
    private javax.swing.JRadioButton rbtn6caras;
    private javax.swing.JRadioButton rbtn8caras;
    // End of variables declaration//GEN-END:variables
}
